# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b8915a75ef4b2b9d573d6201de91eec768917946a1f113807ab0a078490e362b4febd9c096e4027e2fea3ed96d96b42d83a636489242c47ec282773060493ee

test:
  secret_key_base: 4def5911363649ad25a2e2965112f297a774092853f27a0994bcd7de5c6e582df13405d804b024237256bb3b3960706fe6012dc6f0cc1026b6912a5fd384c0e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
